name: Robot Framework Front Tests

on: [push, workflow_dispatch]

jobs:
  test:
    name: Front Tests Robot
    runs-on: ubuntu-24.04

    steps:
      - name: Clonar arquivos do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalação das Dependencias
        run: |
          pip install robotframework
          pip install --upgrade robotframework-seleniumlibrary
          pip install Faker
          pip install pyyaml

      - name: Executando os testes de Front do Robot
        run: |
          robot --variable BROWSER:firefox --outputdir results/ .

      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-front-report
          path: results
